sudo: false
dist: trusty
language: node_js
node_js: stable

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  google-chrome: latest

install:
  - npm install npm@5 -g
  - npm install
  - polymer install

before_script:
  - gulp lint
  - polymer lint --rules polymer-2 --input *.html
  - xvfb-run -s '-screen 0 1024x768x24' polymer test
  - travis_retry xvfb-run -s '-screen 0 1024x768x24' gulp perf:run

script:
  - gemini test test/visual
  - if [[ "$TRAVIS_EVENT_TYPE" == "push" && "$TRAVIS_BRANCH" != quick/* ]]; then
      xvfb-run -s '-screen 0 1024x768x24' polymer test --env saucelabs;
    fi
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
      xvfb-run -s '-screen 0 1024x768x24' polymer test --env saucelabs-cron;
    fi
