sudo: true
dist: trusty
language: node_js
node_js: 8.9

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  chrome: stable

env:
  - POLYMER=polymer2
  - POLYMER=polymer3

script:
  - if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" && "$TRAVIS_BRANCH" != quick/* ]]; then
      if [[ "$POLYMER" = "polymer2" ]]; then
        npm install;
        bower install;
        gulp lint;
        polymer lint --rules polymer-2 --input *.html;
        polymer test --env saucelabs;
      fi;
      if [[ "$POLYMER" = "polymer3" ]]; then
        npm install -g bower json web-component-tester@next yarn;
        (cd .. && git clone git://github.com/polymer/polymer-modulizer.git && cd polymer-modulizer && npm link);
        json -I -f package.json -e 'this.devDependencies = {}';
        bower i;
        modulizer --out . --force;
        yarn install --flat;
        wct --module-resolution=node --npm --env saucelabs-p3;
      fi;
    fi
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
      npm install;
      polymer test --env saucelabs-cron;
    fi
