sudo: true
dist: xenial
language: node_js
node_js: 8.11

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  chrome: stable

before_script:
  - npm install -g bower polymer-cli
  - bower install

env:
  - POLYMER=2
  - POLYMER=3

script:
  - if [[ "$POLYMER" = "2" ]]; then
      npm install &&
      npm run lint &&
      if [[ "$TRAVIS_EVENT_TYPE" = "pull_request" ]]; then
        xvfb-run -s '-screen 0 1024x768x24' wct;
      else
        wct --env saucelabs;
      fi;
    fi

  - if [[ "$POLYMER" = "3" ]]; then
      npm install -g yarn magi-cli polymer-modulizer web-component-tester &&
      rm -rf node_modules &&
      magi p3-convert --out . --import-style=name &&
      yarn install --flat &&
      if [[ "$TRAVIS_EVENT_TYPE" = "pull_request" ]]; then
        xvfb-run -s '-screen 0 1024x768x24' wct --npm;
      else
        wct --npm --env saucelabs;
      fi;
    fi

  - if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then
      npm install &&
      wct --env saucelabs-cron;
    fi
