sudo: true
dist: trusty
language: node_js
node_js: 8.1

cache:
  directories:
    - node_modules

addons:
  chrome: stable
  firefox: latest
  ssh_known_hosts: app.fi

install:
  - npm install
  - bower install

deploy:
  - provider: script
    script: "./.travis.deploy.sh"
    skip_cleanup: true
    on:
      branch: master

before_script:
  - gulp lint version:check
  - polymer lint --rules polymer-2 --input *.html
  - xvfb-run -s '-screen 0 1024x768x24' polymer test

script:
  - if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" && "$TRAVIS_BRANCH" != quick/* ]]; then
      npm i gemini@^4.0.0 gemini-sauce gemini-polyserve;
      gemini test test/visual;
      gemini test test/visual -c .gemini-ie.yml;
      xvfb-run -s '-screen 0 1024x768x24' polymer test --env saucelabs;
    fi
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
      xvfb-run -s '-screen 0 1024x768x24' polymer test --env saucelabs-cron;
    fi

before_deploy:
  - openssl aes-256-cbc -K $encrypted_ccccac989772_key -iv $encrypted_ccccac989772_iv
    -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
