sudo: false
dist: trusty
language: node_js
node_js: stable

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  google-chrome: latest

install:
  - npm install
  - polymer install

before_script:
  - gulp lint
  - ([ "$TRAVIS_EVENT_TYPE" = "pull_request" ] || TRAVIS_BRANCH=quick/${TRAVIS_BUILD_ID} xvfb-run -s '-screen 0 1024x768x24' polymer test) 

script:
  - xvfb-run -s '-screen 0 1024x768x24' wct
  - rm -rf bower_components
  - mv bower_components-polymer2 bower_components
  - cp bower-polymer2.json bower.json
  - cp wct.conf-2.0.js wct.conf.js
  - cp test/index-2.0.html test/index.html
  - xvfb-run -s '-screen 0 1024x768x24' wct
