sudo: true
dist: trusty
language: node_js
node_js: 8.9

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  google-chrome: latest

install:
  - npm install
  - bower install

before_script:
  - gulp lint version:check
  - polymer lint --rules polymer-2 --input ./src/*.html ./theme/**/*.html
  - xvfb-run -s '-screen 0 1024x768x24' wct

script:
  - if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" && "$TRAVIS_BRANCH" != quick/* ]]; then
      npm i gemini@^4.0.0 gemini-sauce gemini-polyserve &&
      gemini test test/visual &&
      gemini test test/visual -c .gemini-ie-ff.yml &&
      wct --env saucelabs;
    fi
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
      wct --env saucelabs-cron;
    fi
