sudo: true
dist: trusty
language: node_js
node_js: 8.9

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  chrome: stable

install:
  - npm install
  - bower install

before_script:
  - gulp lint version:check
  - polymer lint --rules polymer-2 --input ./src/*.html ./theme/**/*.html
  - xvfb-run -s '-screen 0 1024x768x24' wct

env:
  - TEST_SUITE=visual_tests
  - TEST_SUITE=unit_tests

script:
  - if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" && "$TRAVIS_BRANCH" != quick/* ]]; then
      if [[ "$TEST_SUITE" = "visual_tests" ]]; then
        npm i --no-save gemini@^4.0.0 gemini-sauce gemini-polyserve &&
        gemini test test/visual && gemini test test/visual -c .gemini-chrome.yml;
      fi &&
      if [[ "$TEST_SUITE" = "unit_tests" ]]; then
        wct --env saucelabs;
      fi;
    fi
  - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
      if [[ "$TEST_SUITE" = "unit_tests" ]]; then
        wct --env saucelabs-cron;
      fi;
    fi

after_success:
  - "cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls"
