sudo: false
dist: trusty
language: node_js
node_js: 8.11

cache:
  directories:
    - node_modules

addons:
  firefox: "62.0.3"
  chrome: stable

jobs:
  include:
    - if: type = push
      env: TEST_SUITE=unit_tests POLYMER=2
    - if: type = push
      env: TEST_SUITE=unit_tests POLYMER=3
    - if: type = pull_request
      env: POLYMER=2
      addons:
        firefox: "62.0.3"
        chrome: stable
    - if: type = pull_request
      env: POLYMER=3
      addons:
        firefox: "62.0.3"
        chrome: stable
    - if: type = cron
      env: TEST_SUITE=unit_tests POLYMER=2

script:
  - if [[ "$POLYMER" = "2" ]]; then
      npm -q i && npm i -q --no-save bower polymer-cli && bower -q i &&
      if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" && "$TRAVIS_BRANCH" != quick/* ]]; then
        wct --env saucelabs;
      else
        npm run check &&
        npm run lint &&
        wct;
      fi &&
      if [[ "$TRAVIS_EVENT_TYPE" = "cron" && "$TEST_SUITE" = "unit_tests" ]]; then
        wct --env saucelabs-cron;
      fi;
    fi
  - if [[ "$POLYMER" = "3" ]]; then
      npm --no-save -q install -g yarn bower magi-cli web-component-tester polymer-modulizer &&
      rm -rf node_modules &&
      magi p3-convert --out . --import-style=name &&
      yarn install --flat &&
      if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" && "$TRAVIS_BRANCH" != quick/* ]]; then
        wct --npm --env saucelabs;
      else
        wct --npm;
      fi;
    fi
