sudo: true
dist: trusty
language: node_js
node_js: 8.11

cache:
  directories:
    - node_modules

addons:
  firefox: latest
  chrome: stable

before_script:
  - npm install -g bower polymer-cli
  - bower install

env:
  - POLYMER=2
  - POLYMER=3

script:
  - if [[ "$POLYMER" = "2" ]]; then
      npm install &&
      gulp lint &&
      polymer lint --rules polymer-2 --input *.html &&
      if [[ "$TRAVIS_EVENT_TYPE" = "pull_request" ]]; then
        xvfb-run -s '-screen 0 1024x768x24' polymer test;
      else
        polymer test --env saucelabs;
      fi;
    fi

  - if [[ "$POLYMER" = "3" ]]; then
      npm install -g yarn magi-cli &&
      (cd .. && git clone --depth 1 -b vaadin-components-rc git://github.com/web-padawan/polymer-modulizer.git && cd polymer-modulizer && npm link) &&
      rm -rf node_modules &&
      magi p3-convert --out . --import-style=name &&
      yarn install --flat &&
      if [[ "$TRAVIS_EVENT_TYPE" = "pull_request" ]]; then
        xvfb-run -s '-screen 0 1024x768x24' polymer test --module-resolution=node --npm;
      else
        polymer test --module-resolution=node --npm --env saucelabs;
      fi;
    fi

  - if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then
      npm install &&
      polymer test --env saucelabs-cron;
    fi
