sudo: false
dist: trusty
language: node_js
node_js: 8.11

cache:
  directories:
    - node_modules

jobs:
  include:
    - if: type = push
      env: TEST_SUITE=mobile POLYMER=2
    - if: type = push
      env: TEST_SUITE=desktop POLYMER=2
    - if: type = push
      env: TEST_SUITE=mobile POLYMER=3
    - if: type = push
      env: TEST_SUITE=desktop POLYMER=3
    - if: type = pull_request
      env: POLYMER=2
      addons:
        firefox: latest
        chrome: stable
    - if: type = pull_request
      env: POLYMER=3
      addons:
        firefox: latest
        chrome: stable
    - if: type = cron
      env: TEST_SUITE=cron

script:
  - if [[ "$POLYMER" = "2" ]]; then
      npm -q i && npm i -q --no-save bower polymer-cli && bower -q i &&
      gulp lint &&
      polymer lint --rules polymer-2 --input ./src/*.html ./theme/**/*.html &&
      if [[ "$TRAVIS_EVENT_TYPE" = "pull_request" ]]; then
        xvfb-run -s '-screen 0 1024x768x24' wct;
      else
        wct --env saucelabs:$TEST_SUITE;
      fi;
    fi

  - if [[ "$POLYMER" = "3" ]]; then
      npm --no-save -q install -g yarn bower magi-cli web-component-tester polymer-modulizer &&
      rm -rf node_modules &&
      magi p3-convert --out . --import-style=name &&
      yarn install --flat &&
      if [[ "$TRAVIS_EVENT_TYPE" = "pull_request" ]]; then
        xvfb-run -s '-screen 0 1024x768x24' wct --module-resolution=node --npm;
      else
        wct --module-resolution=node --npm --env saucelabs:$TEST_SUITE;
      fi;
    fi

  - if [[ "$TRAVIS_EVENT_TYPE" = "cron" ]]; then
      npm install &&
      wct --env saucelabs:$TEST_SUITE;
    fi

after_success:
  - "cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls"
