sudo: false
dist: trusty
language: node_js
node_js: 8.0

cache:
  directories:
    - node_modules
    - bower_components

install:
  - npm install
  - polymer install

before_script:
  - gulp lint
  #- polymer lint --rules polymer-2 --input *.html
  # - xvfb-run -s '-screen 0 1024x768x24' polymer test -l chrome
  # - xvfb-run -s '-screen 0 1024x768x24' polymer test -l firefox

script:
  - xvfb-run -s '-screen 0 1024x768x24' polymer test --env saucelabs --expanded --verbose
  #- if [[ "$TRAVIS_EVENT_TYPE" != "pull_request" && "$TRAVIS_BRANCH" != quick/* ]]; then
  #    npm i gemini@^4.0.0 gemini-sauce gemini-polyserve;
  #    gemini test test/visual;
  #  fi
  # - if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
  #     xvfb-run -s '-screen 0 1024x768x24' polymer test --env saucelabs-cron;
  #   fi

after_success:
  # - "cat ${TRAVIS_BUILD_DIR}/coverage/lcov.info | coveralls"
