language: node_js
sudo: required
node_js: stable
before_install:
- npm install -g bower
- bower install
- npm install -g web-component-tester
script:
- xvfb-run wct --plugin sauce test
env:
  global:
  - secure: q+Uox1dQe2TeSADXR76ytS2UjVHDRB94/2XoUf+dnMHBjo+5s7MNGxOU0pojzonoAgnjvjDY0C1YpgPHxP2a+hy/4szXzfHHtDUFMKr9kVD+zrluHpux4ubj2WFRwdSJHPP8I77ZmdeLM9w/T9ksZOV6kp2xR9+CyoejnguwsGZu0ORD1v8Yr0xEmbIvrGqovz1XeHQedACu7FDOXXJdF5L0nQ+yuTfDhJyUyeYk1CtQGbvt+7Q5vtzbSzy43gXP8Rb/TTFw2q78nDGz3uYMFy6XHZsr7MdhXqQ9SFfmvb0GTzsB7ph3tPtu9rg1mOms5liFbjqBvbuE6yuwpspCQNWkiyXbkg45ZlIG1rJxUOySDQQegPOIq8zdiOktzsnynIeCngQh/Di1twlLqBGL0Z+8rfEP+9X2+O2h1iPN8byQ0vF6BCEnwvqWSG5Vsey3FiatbZbFrX91CTKJq/5T47+u4468ogBv1vT6YhGclfl77oSX5FlHH0FdIyHMtzhrnmof2NFQ5VdxCT8kjAf+sd+QsjX4lSByKH10XxcfrwZzNZ17XEL5jlc6kUrEtKjKs8AichzfbwxC0x702iJrMqNfn+fI3To2wdOEkEtbwrUPkl4d4jwl4BXjRzxNFRlQbuTDpnLM5njW66DMZ5hHsEUT4kjinZOrPMc54hmc50I=
  - secure: Kn08gFi6239KWICCM88NKYDCPaABE0TweSwNVAjzg/viQJ3iF4yLraLi3silDBSxP9zDFLxI+6tFnmkvyMyNRZtTG9UWbJRiMSxRCH09F38kO+uRAjjDxfK83WBA03iuXhfRUWwrjSuy8cQPgqXWBuLxpIXt8eT3saejzWWe51dLgMz7gdsz1h57A0KlU2Yj5W2/Vmu5CbwRqijz36g//Y+hycT93QTuQmfywXa77DOglHdUBao4V8/jrsD5JoUjFOMaXTbJ44muRlY9YWPolycNbC6unPAkjBqgbn/FAhmW5Zt1IBCXmxlwAXyLQxJA7yKNGw57cEphW79/mrHcSTsyFE9CD3ygKHoIw88Nw0MsvDEDTH4VyoPZCfAKL0/fI/VGm/K86cQ8OIkedxzBKiyx8NT7MfT3gfJV9DRN8fNp2M93DV9XsIsbd92qfozf0SBck+bXZ3KAiQ2YM5g9G818CJb/oa+vHuMylW6pYshj24VzcxUCKmMC3s4UNEBP76sbFjBEqzfhzpNZoYWj6aB+0qTJBpdrm3IDAtI6/dZo3TdjZqX5fOrL8pDTPe9OLlL8LXNUzdDBa/dETrdi6f7f0LqKErDuZU2adb/41baj4JHiMSWfgjWxXo8Nx7OtzavVZkVW2mmD3hYtuCMQpU5Q7WvDOxCPyPoaM2aw0l0=
notifications:
  flowdock:
    on_failure: change
    secure: W4ZVIYWhKGnFzchvSFhYfpyxPW0AeJklw+Rx9JNuFW5ymPnSoN4ztAgql3f9rZb9G8MTcYzZJzrSM0ODVVbn/scgPQHkgJhJ7hoBwMamQFClNu+8sPMZwlBs9Oyawq5RWQBqk+000NKxjWIU2E6yMioAIvtfee2Mod0CfDIlzUlFCIih38xaJ6JYJCa/F6rWl8wSUuKs83GoL6qDjXUFxS+jKtDbZcL/kYGJiK4uPGUt9ZMoqMMD4XiOEmNXsf1Qj9xmmPhpoJtnkrj+q79Tdu+e0FKid0sbJwvO1A3kW0FuVztSv/P8GH0E3ILMBBA6msv+P1YP01pLxH+4pTr3UEttdkINKbK2uSu2xC0D0Ztne1UwxuiSZXynGxuMuZwR/2ekMp8T9LLF50MxIlj7ysQy2AbUrfZhLCIAInzaIdyK4iVGS1XVKnR0VoHD33TQ4JfMw9chO1YHBJVXRPuTJ5yzjv3Cw+QiwHMEhqUyvkPPwprK5AI2Pc/CZzKad52r9hE7FiChsvpYSxTBEpBFGWHWhqyqgyKOCZ7p6nxI442bLkwfx8xyIQTtJUucg2UaeFFjykX0iETg31XVc2SvUpeA5DifUGsRtu+np/E/DuNEkB81xN8iMgMxfwAQYIM/POt2tGWAkiyHPMRj3o+ZTQSD44PwnBLDF5QQGbHx2Kw=
cache:
  directories:
  - node_modules